modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="lootrteams"
version="${file.jarVersion}"
displayName="Lootr Teams Addon"
description="Team-based shared loot for Lootr."

[[dependencies.lootrteams]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lootrteams]]
    modId="lootr"
    mandatory=true
    versionRange="[0.7,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.lootrteams]]
    modId="ftbteams"
    mandatory=false
    versionRange="[2001,)"
    ordering="BEFORE"
    side="BOTH"
